// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter;

#nullable disable

namespace Production.EmmaCabCompany.Migrations
{
    [DbContext(typeof(CabContext))]
    [Migration("20241026162347_AddConstraint")]
    partial class AddConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Production.EmmaCabCompany.Cab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cab")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_cabName")
                        .HasColumnType("TEXT")
                        .HasColumnName("CabName");

                    b.Property<double>("_latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<double>("_longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<int>("_wallet")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Wallet");

                    b.HasKey("Id");

                    b.HasIndex("Cab");

                    b.ToTable("Cabs");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Domain.Fleet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fleet");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Cab", b =>
                {
                    b.HasOne("Production.EmmaCabCompany.Domain.Fleet", null)
                        .WithMany("FleetOfCabs")
                        .HasForeignKey("Cab");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Domain.Fleet", b =>
                {
                    b.Navigation("FleetOfCabs");
                });
#pragma warning restore 612, 618
        }
    }
}
