// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter;

#nullable disable

namespace Production.EmmaCabCompany.Migrations
{
    [DbContext(typeof(CabContext))]
    [Migration("20241124142923_BringUpToCurrentState")]
    partial class BringUpToCurrentState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.CustomerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CustomerId");

                    b.Property<string>("EndLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndLocation");

                    b.Property<int?>("MenuId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MenuId");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerName");

                    b.Property<string>("StartLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartLocation");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.CustomerListDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CustomerList");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Fleet.Fleet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fleet");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Menu.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Cab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cab")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CabId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_cabName")
                        .HasColumnType("TEXT")
                        .HasColumnName("CabName");

                    b.Property<double>("_latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<double>("_longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<int>("_wallet")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Wallet");

                    b.HasKey("Id");

                    b.HasIndex("Cab");

                    b.HasIndex("CabId");

                    b.ToTable("Cabs");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.CustomerDto", b =>
                {
                    b.HasOne("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.CustomerListDto", null)
                        .WithMany("Customers")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Menu.Menu", null)
                        .WithMany("Customers")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Cab", b =>
                {
                    b.HasOne("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Fleet.Fleet", null)
                        .WithMany("FleetOfCabs")
                        .HasForeignKey("Cab");

                    b.HasOne("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Menu.Menu", null)
                        .WithMany("Cabs")
                        .HasForeignKey("CabId");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.CustomerListDto", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Fleet.Fleet", b =>
                {
                    b.Navigation("FleetOfCabs");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Menu.Menu", b =>
                {
                    b.Navigation("Cabs");

                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
