// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter;

#nullable disable

namespace Production.EmmaCabCompany.Migrations
{
    [DbContext(typeof(CabContext))]
    [Migration("20250427104527_MakeCustomerIdNullable")]
    partial class MakeCustomerIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.CustomerList.PatronDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndLocation");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerName");

                    b.Property<string>("StartLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartLocation");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Patrons");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Fleet.CabDriver", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_cabName")
                        .HasColumnType("TEXT")
                        .HasColumnName("CabName");

                    b.Property<double>("_latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<double>("_longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<int>("_status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.Property<int>("_wallet")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Wallet");

                    b.HasKey("Id");

                    b.ToTable("CabDrivers");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.CustomerList.PatronDto", b =>
                {
                    b.HasOne("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Fleet.CabDriver", b =>
                {
                    b.HasOne("Production.EmmaCabCompany.Adapter.OutAdapter.CabFileAdapter.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
