// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Production.EmmaCabCompany.Adapter.@out.CabFileAdapter;

#nullable disable

namespace Production.EmmaCabCompany.Migrations
{
    [DbContext(typeof(CabContext))]
    partial class CabContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Production.EmmaCabCompany.Domain.Fleet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fleet");
                });
#pragma warning restore 612, 618
        }
    }
}
